import { useState } from 'react';
import { AlertTriangle, ArrowRight, Boxes, CheckCircle2, Gauge, PackageCheck, Scissors, Shirt, UsersRound } from 'lucide-react';
import { apparelLines } from '../domain/data';
import { useDemo } from '../state/DemoContext';
import { PageHeader } from '../components/ui/PageHeader';
import { StatusBadge } from '../components/ui/StatusBadge';

const stations=[['Cutting',Scissors,100],['Bundling',Boxes,96],['Sewing',Shirt,78],['Inline QC',CheckCircle2,71],['Finishing',SparkIcon,68],['Packing',PackageCheck,62]];
function SparkIcon(){return <Gauge/>}

export function ApparelOperationsPage(){
  const {notify}=useDemo(); const [line,setLine]=useState(apparelLines[0]);
  const hours=[['08',72,68],['09',105,101],['10',112,108],['11',118,96],['12',86,79],['13',120,104],['14',122,110],['15',105,92]];
  return <div className="page"><PageHeader eyebrow={<><span className="live-dot"/> APPAREL FLOOR • SHIFT B</>} title="Apparel production control" subtitle="Orders, line flow and quality signals from cut panels through packed garments." actions={<button className="primary" onClick={()=>notify('Line-balancing scenario calculated')}><Gauge/> Rebalance line</button>}/>
    <div className="line-selector card">{apparelLines.map(item=><button className={item.id===line.id?'active':''} onClick={()=>setLine(item)} key={item.id}><span><b>{item.id}</b><small>{item.style}</small></span><strong>{item.efficiency}%</strong><StatusBadge tone={item.status==='At risk'?'Critical':item.status==='Attention'?'High':'Low'}>{item.status}</StatusBadge></button>)}</div>
    <div className="apparel-kpis"><div className="card"><UsersRound/><span><small>Line efficiency</small><b>{line.efficiency}%</b><em className={line.efficiency<85?'bad':'good'}>{line.efficiency<85?'Below 88% target':'Above target'}</em></span></div><div className="card"><Shirt/><span><small>Output today</small><b>{line.actual}<em> pcs</em></b><em>{line.target-line.actual} behind target</em></span></div><div className="card"><Boxes/><span><small>Work in progress</small><b>{line.wip}<em> pcs</em></b><em className={line.wip>140?'bad':'good'}>{line.wip>140?'Buffer elevated':'Flow balanced'}</em></span></div><div className="card"><CheckCircle2/><span><small>DHU quality</small><b>{line.defects}%</b><em className={line.defects>2?'bad':'good'}>{line.defects>2?'Review required':'Within 2% target'}</em></span></div></div>
    <section className="card order-banner"><div><span>LIVE ORDER</span><h2>{line.order} • {line.style}</h2><p>{line.buyer} • 4,800 pieces • Ship 26 Aug</p></div><div className="order-progress"><span><b>3,124</b> completed</span><i><i style={{width:'65%'}}/></i><small>65% order completion • on-time probability 84%</small></div><button onClick={()=>notify(`${line.order} detail opened`)}>Order detail <ArrowRight/></button></section>
    <section className="card sewing-flow"><div className="card-head"><div><h2>Live line flow</h2><p>Bundle movement and station capacity • updates every 30 seconds</p></div><span className="line-live"><i/> {line.operators} operators clocked in</span></div><div className="station-track">{stations.map(([label,Icon,rate],index)=>{const bottleneck=(line.id==='LINE-01'&&label==='Sewing')||(line.id==='LINE-03'&&label==='Inline QC');return <div className={`station ${bottleneck?'bottleneck':''}`} key={label}><span><Icon/></span><small>0{index+1}</small><b>{label}</b><strong>{bottleneck?line.bottleneck:`${rate}% flow`}</strong><em>{bottleneck?'Queue building':'Normal cadence'}</em>{index<stations.length-1&&<i className="station-link"><i/><i/></i>}</div>})}</div>{line.bottleneck!=='None'&&<div className="bottleneck-callout"><AlertTriangle/><span><b>Bottleneck detected at {line.bottleneck}</b><small>WIP increased 18% in the last 40 minutes. Moving one trained operator could recover approximately 34 pieces this shift.</small></span><button onClick={()=>notify('Rebalancing recommendation sent for supervisor review')}>Review recommendation</button></div>}</section>
    <div className="apparel-detail-grid"><section className="card hourly-output"><div className="card-head"><div><h2>Hourly output</h2><p>Target versus completed pieces</p></div><div className="output-legend"><span><i/>Actual</span><span><i/>Target</span></div></div><div className="hour-bars">{hours.map(([hour,target,actual])=><div key={hour}><span>{hour}:00</span><i><i style={{height:`${actual/1.25}px`}}/><em style={{bottom:`${target/1.25}px`}}/></i><b>{actual}</b></div>)}</div></section><aside className="card line-events"><div className="card-head"><div><h2>Live line events</h2><p>Operational and quality exceptions</p></div></div>{[['14:12','WIP threshold exceeded','Collar attach • 46 bundles','High'],['13:48','Inline quality check','Seam pucker • 3 pieces','Medium'],['13:21','Operator allocation changed','2 operators moved to sleeve','Low'],['12:56','Bundle completed','BND-0842 • 24 pieces','Low']].map(event=><div key={event[0]}><time>{event[0]}</time><i className={event[3].toLowerCase()}/><span><b>{event[1]}</b><small>{event[2]}</small></span></div>)}</aside></div>
  </div>
}
