import { useState } from 'react';
import { ArrowDownRight, ArrowUpRight } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import { PageHeader } from '../components/ui/PageHeader';
import { StatusBadge } from '../components/ui/StatusBadge';

const reliability=[66,68,67,71,70,74,73,77,78,80,79,84];
const labels=['Jul 22','Jul 25','Jul 28','Jul 31','Aug 03','Aug 06','Aug 09','Aug 12','Aug 15','Aug 18','Aug 20','Aug 21'];
function ReliabilityChart(){
  const [hovered,setHovered]=useState(null);const left=62,right=820,top=30,bottom=242,min=60,max=90;
  const x=index=>left+index*((right-left)/(reliability.length-1)),y=value=>bottom-(value-min)/(max-min)*(bottom-top);
  const path=reliability.map((value,index)=>`${index?'L':'M'} ${x(index)} ${y(value)}`).join(' ');
  return <div className="reliability-chart"><svg viewBox="0 0 860 295" role="img" aria-label="Fleet reliability score trend"><defs><linearGradient id="reliabilityFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#117964" stopOpacity=".22"/><stop offset="1" stopColor="#117964" stopOpacity="0"/></linearGradient></defs>{[60,65,70,75,80,85,90].map(value=><g className="chart-grid-row" key={value}><line x1={left} y1={y(value)} x2={right} y2={y(value)}/><text x={left-14} y={y(value)+4} textAnchor="end">{value}</text></g>)}{[0,3,6,9,11].map(index=><text className="analytics-x-label" key={index} x={x(index)} y="274" textAnchor={index===0?'start':index===11?'end':'middle'}>{labels[index]}</text>)}<path d={`${path} L ${right} ${bottom} L ${left} ${bottom} Z`} fill="url(#reliabilityFill)"/><path d={path} className="reliability-line"/>{reliability.map((value,index)=><g key={index} onMouseEnter={()=>setHovered(index)} onMouseLeave={()=>setHovered(null)}><circle className="hit-target" cx={x(index)} cy={y(value)} r="13"/><circle className={index===11?'analytics-point latest':'analytics-point'} cx={x(index)} cy={y(value)} r={index===11?6:3.5}/></g>)}{hovered!==null&&<g className="chart-tooltip" transform={`translate(${Math.min(x(hovered),right-70)},${Math.max(y(reliability[hovered])-60,4)})`}><rect x="-54" width="108" height="45" rx="7"/><text x="-41" y="18">{labels[hovered]}</text><text x="-41" y="35" className="tooltip-value">Score {reliability[hovered]} / 100</text></g>}</svg></div>
}

export function OptimizePage(){const navigate=useNavigate();return <div className="page"><PageHeader eyebrow="CROSS-ASSET ANALYTICS" title="Optimize" subtitle="Reliability, maintenance and shade performance across Plant A." actions={<button className="secondary">Last 30 days⌄</button>}/><div className="opt-grid"><section className="card opt-chart"><div className="card-head"><div><h2>Reliability score trend</h2><p>Fleet-wide health indicator across monitored assets</p></div><b className="good"><ArrowUpRight/> +4.2%</b></div><ReliabilityChart/><div className="analytics-summary"><span><small>Current score</small><b>84.0</b></span><span><small>30-day change</small><b className="good">+4.2%</b></span><span><small>Assets contributing</small><b>128</b></span><span><small>Data completeness</small><b>98.9%</b></span></div></section><section className="card"><div className="card-head"><div><h2>Risk by process</h2><p>Assets warning or critical</p></div></div><div className="bars">{[['Weaving',8,48],['Utilities',3,11],['Dyeing',2,18],['Finishing',1,14],['Cut & Sew',2,37]].map(item=><div key={item[0]}><span>{item[0]}</span><i><i style={{width:`${item[1]/item[2]*100}%`}}/></i><b>{item[1]}</b><small>/ {item[2]}</small></div>)}</div></section><section className="card"><div className="card-head"><div><h2>Maintenance outcomes</h2><p>Closed work orders by result</p></div></div><div className="metric-stack"><div><b>87%</b><span>Verified resolution rate</span><small className="good"><ArrowUpRight/> 5% this month</small></div><div><b>5.8h</b><span>Mean time to action</span><small className="good"><ArrowDownRight/> 1.2h</small></div><div><b>28</b><span>Orders completed</span><small>Last 30 days</small></div></div></section><section className="card shade-analytics"><div className="card-head"><div><h2>Shade performance</h2><p>Batch quality is measured separately from asset health</p></div><StatusBadge tone="Low">93.5% pass</StatusBadge></div><div className="shade-ring"><div><b>116</b><span>Pass</span></div></div><div className="shade-values"><div><i className="dot green"/><span>Pass</span><b>116</b></div><div><i className="dot red"/><span>Fail</span><b>8</b></div><button onClick={()=>navigate('/shade')}>Open color intelligence →</button></div></section></div></div>}
