import { useEffect, useMemo, useState } from 'react';
import { Activity, Beaker, Check, Clock3, Droplets, FlaskConical, Pause, Play, Save, Sparkles, ThermometerSun } from 'lucide-react';
import { liveColorBatch } from '../domain/data';
import { evaluateShadeRule } from '../domain/logic';
import { useDemo } from '../state/DemoContext';
import { PageHeader } from '../components/ui/PageHeader';
import { StatusBadge } from '../components/ui/StatusBadge';

export function ShadeQualityPage(){
  const {batches,shadeTolerance,saveShadeTolerance,notify}=useDemo();
  const [draft,setDraft]=useState(shadeTolerance),[elapsed,setElapsed]=useState(liveColorBatch.elapsed),[running,setRunning]=useState(true),[applied,setApplied]=useState(false),[view,setView]=useState('live');
  useEffect(()=>{if(!running)return;const timer=window.setInterval(()=>setElapsed(value=>value>=liveColorBatch.duration?liveColorBatch.elapsed:value+1),2600);return()=>window.clearInterval(timer)},[running]);
  const predicted=Math.max(.58,liveColorBatch.predictedDeltaE+(elapsed-liveColorBatch.elapsed)*.002);
  const results=useMemo(()=>batches.map(batch=>({...batch,...evaluateShadeRule(batch.deltaE,shadeTolerance)})),[batches,shadeTolerance]);
  const pass=results.filter(item=>item.result==='Pass').length;
  const progress=elapsed/liveColorBatch.duration*100;
  const pointX=62+progress*4.85, pointY=205-Math.min(1,predicted)*98;
  const jump=(next,selector)=>{setView(next);document.querySelector(selector)?.scrollIntoView({behavior:'smooth',block:'start'})};
  return <div className="page color-page"><PageHeader eyebrow={<><span className="live-dot"/> SMARTMILL COLOR • LIVE BATCH</>} title="Color intelligence" subtitle="Predict shade outcome during production, explain the recommendation, and verify the final batch against the customer rule." actions={<><button className="secondary" onClick={()=>setRunning(!running)}>{running?<Pause/>:<Play/>}{running?'Pause stream':'Resume stream'}</button><button className="primary" onClick={()=>notify('New lab dip workflow opened')}><Beaker/> New lab dip</button></>}/>
    <div className="module-tabs"><button className={view==='live'?'active':''} onClick={()=>jump('live','.live-batch-banner')}>Live batch</button><button className={view==='lab'?'active':''} onClick={()=>jump('lab','.rule-workbench')}>Shade lab</button><button className={view==='history'?'active':''} onClick={()=>jump('history','.compact-batches')}>Batch history</button><span><i/> Spectrophotometer connected</span></div>
    <section className="card live-batch-banner"><div><span>RUNNING ON {liveColorBatch.machine}</span><h2>{liveColorBatch.id} • {liveColorBatch.style}</h2><p>{liveColorBatch.fabric} • {liveColorBatch.customer} • {liveColorBatch.order}</p></div><div className="batch-clock"><Clock3/><span><b>{elapsed}</b> / {liveColorBatch.duration} min</span><i><i style={{width:`${progress}%`}}/></i><small>Dye circulation • on recipe</small></div><StatusBadge tone="Low">LIVE</StatusBadge></section>
    <div className="color-kpis"><div className="card"><Droplets/><span><small>Predicted ΔE at drop</small><b>{predicted.toFixed(2)}</b><em className="good">Pass ≤ {shadeTolerance.toFixed(2)}</em></span></div><div className="card"><ThermometerSun/><span><small>Bath temperature</small><b>{liveColorBatch.temperature}<em>°C</em></b><em className="good">On curve</em></span></div><div className="card"><Sparkles/><span><small>Recipe confidence</small><b>{liveColorBatch.recipeConfidence}<em>%</em></b><em>{liveColorBatch.similarLots} similar lots</em></span></div><div className="card"><Activity/><span><small>Energy so far</small><b>Rs {liveColorBatch.energy}k</b><em className="good">8% below average</em></span></div></div>
    <section className="card color-process"><div className="card-head"><div><h2>Batch intelligence flow</h2><p>Each recommendation is connected to recipe history, live process conditions and the approved shade standard.</p></div><span className="decision-live"><i/> Prediction refresh • 10 s</span></div><div className="color-flow">{[['Recipe history','62 comparable lots','complete'],['AI shade prediction',`${predicted.toFixed(2)} ΔE at drop`,'complete'],['Live batch monitoring',`Minute ${elapsed} of ${liveColorBatch.duration}`,'active'],['Mid-cycle correction',applied?'Operator accepted':'Recommendation ready',applied?'complete':'ready'],['Final verification','Spectro reading at drop','queued']].map((step,index)=><div className={`color-flow-step ${step[2]}`} key={step[0]}><i>{step[2]==='complete'?<Check/>:index+1}</i><span><b>{step[0]}</b><small>{step[1]}</small></span>{index<4&&<em><em/></em>}</div>)}</div></section>
    <div className="color-main-grid"><section className="card shade-prediction"><div className="card-head"><div><h2>Shade deviation • predicted versus live</h2><p>Lower ΔE indicates closer agreement with the approved standard.</p></div><span className="tolerance-chip">Tolerance band ≤ {shadeTolerance.toFixed(2)}</span></div><svg viewBox="0 0 600 245" role="img" aria-label="Predicted shade deviation through the current batch"><rect x="62" y="75" width="485" height="100" rx="5" className="shade-band"/><text x="76" y="94">PASS BAND</text>{[0,70,140,210].map((value,index)=><g key={value}><line x1={62+index*161.6} y1="52" x2={62+index*161.6} y2="215"/><text x={54+index*161.6} y="236">{value} min</text></g>)}<path d="M62 205 C130 178 180 141 230 125 S355 92 547 88" className="predicted-path"/><path d={`M62 205 C130 178 180 141 ${pointX} ${pointY}`} className="actual-path"/><circle cx={pointX} cy={pointY} r="7"/><circle cx={pointX} cy={pointY} r="13" className="pulse-ring"/><text x={Math.min(pointX+12,475)} y={pointY-10}>now • {predicted.toFixed(2)} ΔE</text></svg><div className="prediction-legend"><span><i className="actual"/>Live calculated path</span><span><i className="forecast"/>Predicted path</span><b>Projected final: {predicted.toFixed(2)} ΔE</b></div></section>
      <aside className="card recipe-panel"><div className="section-label"><FlaskConical/> AI RECIPE • THIS LOT</div><h2>{liveColorBatch.recipe}</h2><p>Adjusted from lab dip using fabric construction and machine history.</p><div className="ingredients">{liveColorBatch.ingredients.map(item=><div key={item[0]}><span>{item[0]}</span><b>{item[1]}</b></div>)}</div><div className="recipe-source"><Sparkles/><span><b>Why this recipe</b><small>62 comparable lots • same substrate family • DYE-001 correction factor • approved standard v3</small></span></div></aside>
    </div>
    <div className="color-action-grid"><section className={`card recommendation ${applied?'applied':''}`}><div className="recommend-icon">{applied?<Check/>:<Sparkles/>}</div><div><span>{applied?'OPERATOR DECISION RECORDED':'RECOMMENDATION • CONFIDENCE 91%'}</span><h2>{applied?'Hold step added to the batch instruction':'Hold at 130°C for 6 more minutes before rinse'}</h2><p>{applied?'Accepted by Amna Khan at minute '+elapsed+'. The final shade result will still require spectrophotometer verification.':'The live curve is converging slightly faster than comparable lots. A short hold is projected to land at ΔE 0.60 while avoiding a full reheating step.'}<br/><small>Evidence: live curve 46% • recipe history 31% • machine correction factor 23%</small></p></div><button className="primary" disabled={applied} onClick={()=>{setApplied(true);notify('Recommendation added to operator review log')}}>{applied?<><Check/> Applied</>:<>Review & apply</>}</button></section>
      <aside className="card batch-phase"><div className="card-head"><div><h2>Batch phase</h2><p>Live PLC context</p></div></div>{liveColorBatch.phases.map(([phase,state],index)=><div className={index===2?'active':state.toLowerCase()} key={phase}><i>{state==='Complete'?<Check/>:index+1}</i><span><b>{phase}</b><small>{index===2?`${elapsed-32} min elapsed`:state}</small></span><em>{state}</em></div>)}</aside></div>
    <div className="shade-lab-grid"><section className="card rule-workbench"><div className="section-label"><Beaker/> CUSTOMER ACCEPTANCE RULE</div><h2>Navy Apparel Standard</h2><p>STD-NAVY-001 • Version 3 • Azer Apparel Ltd.</p><div className="rule-editor"><span>Measured ΔE</span><strong>≤</strong><label><input type="number" min=".1" max="5" step=".1" value={draft} onChange={event=>setDraft(Number(event.target.value))}/><small>Maximum tolerance</small></label><strong>PASS</strong></div><button className="secondary wide" onClick={()=>saveShadeTolerance(draft)}><Save/> Save rule configuration</button><small>Customer-controlled acceptance threshold; plant teams retain final approval responsibility.</small></section><section className="card compact-batches"><div className="card-head"><div><h2>Recent verified batches</h2><p>{pass}/{results.length} visible batches pass the current rule</p></div></div>{results.map(batch=><button key={batch.id} onClick={()=>notify(`${batch.id} measurement record opened`)}><span><b>{batch.id}</b><small>{batch.machine} • {batch.measured}</small></span><strong>{batch.deltaE.toFixed(2)} ΔE</strong><StatusBadge tone={batch.result==='Pass'?'Low':'Critical'}>{batch.result}</StatusBadge></button>)}</section></div>
  </div>
}
