import { useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, CircleGauge, CloudCog, Plus, RadioTower, ShieldCheck } from 'lucide-react';
import { useNavigate, useParams } from 'react-router-dom';
import { assets, templates } from '../domain/data';
import { MachineReference } from '../components/ui/MachineReference';
import { PageHeader } from '../components/ui/PageHeader';
import { StatusBadge } from '../components/ui/StatusBadge';
import { useDemo } from '../state/DemoContext';

function TemplateCard({template}){const navigate=useNavigate();return <article className="template-card" onClick={()=>navigate(`/templates/${template.id}`)}><MachineReference src={template.image} alt={`${template.name} machinery diagram`} className="template-img" label={template.process}/><div className="template-copy"><div className="template-top"><h3>{template.name}</h3><StatusBadge tone="Low">{template.status}</StatusBadge></div><p>{template.description}</p><div className="template-meta"><span><b>{template.signals}</b> signals</span><span><b>{template.modes}</b> modes</span><span><b>{template.kpis}</b> KPIs</span><span>v{template.version}</span></div><button>Open template <ArrowRight/></button></div></article>}

export function TemplatesPage(){const [filter,setFilter]=useState('All');const shown=filter==='All'?templates:templates.filter(t=>t.process.includes(filter));return <div className="page"><PageHeader eyebrow="CONFIGURATION CATALOGUE" title="Template library" subtitle="Reusable reliability intelligence for textile assets and quality processes." actions={<button className="primary"><Plus/> Create template</button>}/><div className="filterbar">{['All','Weaving','Dyeing','Finishing','Utilities','Cut & Sew','Shade'].map(f=><button key={f} className={filter===f?'active':''} onClick={()=>setFilter(f)}>{f}{f==='All'&&<b>{templates.length}</b>}</button>)}</div><div className="template-grid">{shown.map(t=><TemplateCard key={t.id} template={t}/>)}</div></div>}

export function TemplateDetailPage(){const {templateId}=useParams(),navigate=useNavigate(),{notify}=useDemo();const template=useMemo(()=>templates.find(t=>t.id===templateId)||templates[0],[templateId]);const deployed=assets.filter(a=>a.templateId===template.id);return <div className="page template-detail"><button className="back" onClick={()=>navigate('/templates')}><ArrowLeft/> Template library</button><div className="asset-hero card"><div className="asset-hero-copy"><div className="eyebrow">{template.process.toUpperCase()} • REUSABLE TEMPLATE</div><div className="asset-title"><h1>{template.name}</h1><StatusBadge tone="Low">{template.status}</StatusBadge></div><p>{template.description}</p><div className="hero-health"><div><span>Version</span><b className="date">v{template.version}</b></div><div><span>Signals</span><b>{template.signals}</b></div><div><span>Configured modes</span><b>{template.modes}</b></div><div><span>Deployed assets</span><b>{deployed.length}</b></div></div></div><MachineReference src={template.image} alt={template.name} className="asset-diagram"/></div><div className="tabs"><button className="active">Overview</button><button>Signals</button><button>Components</button><button>Failure Modes</button><button>Models</button><button>Rules & Alerts</button><button>Assets</button></div><div className="template-detail-grid"><section className="card config-section"><div className="card-head"><div><h2>Signal configuration</h2><p>Mapped telemetry and event fields</p></div><StatusBadge tone="Monitoring">{template.signals} mapped</StatusBadge></div><div className="config-list">{template.signalNames.map((name,index)=><div key={name}><span className="config-icon"><RadioTower/></span><span><b>{name}</b><small>{['Time-series','Event count','Operational state'][index%3]} • live mapping</small></span><StatusBadge tone="Low">Mapped</StatusBadge></div>)}</div></section><section className="card config-section"><div className="card-head"><div><h2>Reliability configuration</h2><p>Rules, model and workflow readiness</p></div></div><div className="readiness"><div><ShieldCheck/><span><b>Configuration valid</b><small>Required fields complete</small></span><strong>100%</strong></div><div><CloudCog/><span><b>Model readiness</b><small>Baseline and sensitivity configured</small></span><strong>Ready</strong></div><div><CircleGauge/><span><b>Signal coverage</b><small>{template.signals} of {template.signals} signals mapped</small></span><strong>100%</strong></div></div><h4>Configured degradation modes</h4><ul className="mode-list">{template.failureModes.length?template.failureModes.map(mode=><li key={mode}><Check/>{mode}</li>):<li><Check/>Batch quality rules are maintained separately from asset failure modes.</li>}</ul><button className="primary wide" onClick={()=>notify(`${template.name} deployment draft created`)}>Deploy this template <ArrowRight/></button></section></div></div>}
