import { useState } from 'react';
import { Camera, Check, Crosshair, FileCheck2, ScanLine, Sparkles } from 'lucide-react';
import { visionRoll } from '../domain/data';
import { useDemo } from '../state/DemoContext';
import { PageHeader } from '../components/ui/PageHeader';
import { StatusBadge } from '../components/ui/StatusBadge';

export function VisionInspectionPage(){
  const {notify}=useDemo(); const [selected,setSelected]=useState(visionRoll.defects.at(-1));
  return <div className="page"><PageHeader eyebrow={<><span className="live-dot"/> EDGE VISION • LIVE ROLL</>} title="Woven fabric inspection" subtitle="Every inspected metre is mapped, classified and traced back to its production source." actions={<button className="primary" onClick={()=>notify('Buyer quality certificate draft generated')}><FileCheck2/> Generate certificate</button>}/>
    <div className="vision-kpis"><div className="card"><small>Roll progress</small><b>{visionRoll.inspected}<em> / {visionRoll.length} m</em></b><i><i style={{width:`${visionRoll.inspected/visionRoll.length*100}%`}}/></i></div><div className="card"><small>Defects detected</small><b>{visionRoll.defects.length}</b><span>2 major • 1 critical</span></div><div className="card"><small>Defect density</small><b>{visionRoll.defectRate}<em> /100 m</em></b><span className="good">Within buyer limit</span></div><div className="card"><small>Vision confidence</small><b>{visionRoll.confidence}<em>%</em></b><span className="good">Edge model online</span></div></div>
    <div className="vision-layout"><section className="card fabric-inspection"><div className="card-head"><div><h2>Digital defect map</h2><p>{visionRoll.id} • {visionRoll.style} • {visionRoll.width} width</p></div><span className="camera-live"><Camera/><i/> Camera 02 live</span></div><div className="fabric-map"><div className="fabric-grid"/><div className="scan-beam"><ScanLine/></div>{visionRoll.defects.map(defect=><button key={defect.id} className={`defect-pin ${defect.severity.toLowerCase()} ${selected.id===defect.id?'selected':''}`} style={{left:`${defect.x}%`,top:`${defect.y}%`}} onClick={()=>setSelected(defect)}><i/><span>{defect.meter}m</span></button>)}<div className="fabric-edge left"/><div className="fabric-edge right"/></div><div className="meter-axis"><span>0 m</span><span>65 m</span><span>130 m</span><span>195 m</span><span>260 m</span></div><footer className="inspection-legend"><span><i className="minor"/> Minor</span><span><i className="major"/> Major</span><span><i className="critical"/> Critical</span><b><i/> Inspecting metre {visionRoll.inspected + 1}</b></footer></section>
      <aside className="card defect-detail"><div className="section-label"><Crosshair/> SELECTED DETECTION</div><div className="defect-title"><span><Sparkles/></span><div><small>{selected.id} • METRE {selected.meter}</small><h2>{selected.type}</h2></div><StatusBadge tone={selected.severity==='Critical'?'Critical':selected.severity==='Major'?'High':'Monitoring'}>{selected.severity}</StatusBadge></div><div className="confidence-ring" style={{'--confidence':`${selected.confidence}%`}}><b>{selected.confidence}%</b><span>classification<br/>confidence</span></div><dl><div><dt>Source roll</dt><dd>{visionRoll.id}</dd></div><div><dt>Production batch</dt><dd>{visionRoll.batch}</dd></div><div><dt>Probable source</dt><dd>{visionRoll.loom}</dd></div><div><dt>Disposition</dt><dd>{selected.severity==='Critical'?'Flag for review':'Map and continue'}</dd></div></dl><button className="primary wide" onClick={()=>notify(`${selected.id} added to quality review`)}><Check/> Confirm classification</button><p className="ai-boundary">The model classifies the visible pattern. Final grading and production-cause confirmation remain operator decisions.</p></aside></div>
    <section className="card trace-flow"><div className="card-head"><div><h2>Source traceability</h2><p>Detection context follows the roll back to the producing asset.</p></div></div><div>{[['Camera 02','Image captured'],['Edge model','Pattern classified'],[visionRoll.id,'Defect mapped'],[visionRoll.batch,'Batch linked'],[visionRoll.loom,'Loom context']].map((item,index)=><span key={item[0]} className={index===4?'attention':''}><i>{index+1}</i><b>{item[0]}</b><small>{item[1]}</small>{index<4&&<em><em/></em>}</span>)}</div></section>
  </div>
}
